"use client";

import { useMemo, useState } from "react";

export type MatchStatus="scheduled"|"in_progress"|"completed"|"cancelled";
export type MatchFormValue={played_at:string;competition:string;venue:string;home_team_name:string;away_team_name:string;is_home:boolean;best_of:3|5;status:MatchStatus;notes:string};
export type SetFormValue={set_number:number;home_score:number;away_score:number};
export type RosterFormValue={player_id:string;starter:boolean;sets_played:number;persisted:boolean};
export type MatchPlayerOption={id:string;full_name:string;jersey_number:number;position:string};
export type MatchFormPayload={match:MatchFormValue;sets:SetFormValue[];roster:RosterFormValue[];home_sets:number;away_sets:number};

const statuses:MatchStatus[]=["scheduled","in_progress","completed","cancelled"];
const statusLabels:Record<MatchStatus,string>={scheduled:"Sắp diễn ra / Scheduled",in_progress:"Đang thi đấu / In progress",completed:"Đã kết thúc / Completed",cancelled:"Đã hủy / Cancelled"};
const toLocalDateTime=(value?:string)=>{const date=value?new Date(value):new Date();const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)};

export function MatchFormModal({mode,teamName,players,initialMatch,initialSets=[],initialRoster=[],onClose,onSave}:{mode:"create"|"edit";teamName:string;players:MatchPlayerOption[];initialMatch?:MatchFormValue;initialSets?:SetFormValue[];initialRoster?:RosterFormValue[];onClose:()=>void;onSave:(payload:MatchFormPayload)=>Promise<string|null>}){
  const [form,setForm]=useState<MatchFormValue>(initialMatch??{played_at:toLocalDateTime(),competition:"",venue:"",home_team_name:teamName,away_team_name:"",is_home:true,best_of:5,status:"scheduled",notes:""});
  const [sets,setSets]=useState<SetFormValue[]>(()=>Array.from({length:5},(_,index)=>initialSets.find(set=>set.set_number===index+1)??{set_number:index+1,home_score:0,away_score:0}));
  const [roster,setRoster]=useState<Record<string,RosterFormValue>>(()=>Object.fromEntries(initialRoster.map(item=>[item.player_id,item])));
  const [error,setError]=useState("");const [saving,setSaving]=useState(false);
  const maxSets=form.best_of;
  const enteredSets=sets.filter(set=>set.set_number<=maxSets&&(set.home_score!==0||set.away_score!==0));
  const homeSets=enteredSets.filter(set=>set.home_score>set.away_score).length,awaySets=enteredSets.filter(set=>set.away_score>set.home_score).length;
  const actualSetCount=enteredSets.length;
  const selectedRoster=useMemo(()=>Object.values(roster),[roster]);

  function setHomeTeam(isHome:boolean){setForm(current=>{const oldTeam=current.is_home?current.home_team_name:current.away_team_name;return {...current,is_home:isHome,home_team_name:isHome?teamName:(oldTeam===teamName?"":oldTeam),away_team_name:isHome?(oldTeam===teamName?"":oldTeam):teamName}})}
  function updateSet(setNumber:number,key:"home_score"|"away_score",value:number){setSets(current=>current.map(set=>set.set_number===setNumber?{...set,[key]:value}:set))}
  function togglePlayer(playerId:string,checked:boolean){const previous=roster[playerId];if(!checked&&previous?.persisted)return;setRoster(current=>{const next={...current};if(checked)next[playerId]=previous??{player_id:playerId,starter:false,sets_played:0,persisted:false};else delete next[playerId];return next})}
  function updateRoster(playerId:string,key:"starter"|"sets_played",value:boolean|number){setRoster(current=>({...current,[playerId]:{...current[playerId],[key]:value}}))}
  async function submit(event:React.FormEvent){event.preventDefault();if(saving)return;const errors:string[]=[];if(!form.played_at)errors.push("Ngày thi đấu là bắt buộc.");if(!form.home_team_name.trim())errors.push("Đội nhà không được để trống.");if(!form.away_team_name.trim())errors.push("Đội khách không được để trống.");if(form.home_team_name.trim().toLowerCase()===form.away_team_name.trim().toLowerCase())errors.push("Đội nhà và đội khách phải khác nhau.");if(![3,5].includes(form.best_of))errors.push("Best of chỉ nhận 3 hoặc 5.");if(!statuses.includes(form.status))errors.push("Trạng thái không hợp lệ.");for(const set of sets.filter(item=>item.set_number<=maxSets)){if(!Number.isInteger(set.home_score)||set.home_score<0||!Number.isInteger(set.away_score)||set.away_score<0)errors.push(`Set ${set.set_number}: điểm phải là số nguyên ≥ 0.`);if((set.home_score!==0||set.away_score!==0)&&set.home_score===set.away_score)errors.push(`Set ${set.set_number}: tỷ số không được hòa.`);if(initialSets.some(saved=>saved.set_number===set.set_number)&&set.home_score===0&&set.away_score===0)errors.push(`Set ${set.set_number} đã lưu không thể xóa về 0–0 vì ứng dụng không dùng DELETE.`)}const needed=form.best_of===3?2:3;if(form.status==="completed"&&Math.max(homeSets,awaySets)!==needed)errors.push(`Trận completed Best of ${form.best_of} phải có đội thắng ${needed} set.`);for(const item of selectedRoster){const limit=actualSetCount||form.best_of;if(!Number.isInteger(item.sets_played)||item.sets_played<0||item.sets_played>limit)errors.push(`Sets played phải là số nguyên 0–${limit}.`)}if(errors.length){setError(errors.join(" "));return}setSaving(true);setError("");const saveError=await onSave({match:{...form,home_team_name:form.home_team_name.trim(),away_team_name:form.away_team_name.trim(),competition:form.competition.trim(),venue:form.venue.trim(),notes:form.notes.trim()},sets:enteredSets,roster:selectedRoster,home_sets:homeSets,away_sets:awaySets});if(saveError){setError(saveError);setSaving(false)}}

  return <div className="modal-backdrop" role="presentation"><section className="modal-card match-modal" role="dialog" aria-modal="true"><div className="panel-head"><div><h2>{mode==="create"?"Thêm trận đấu / Add Match":"Chỉnh sửa trận đấu / Edit Match"}</h2><p>Thông tin trận, tỷ số từng set và đội hình.</p></div><button className="icon-btn" type="button" disabled={saving} onClick={onClose}>×</button></div><form onSubmit={submit} className="form-section"><h3>Thông tin trận / Match Information</h3><div className="form-grid"><div className="field"><label>Ngày giờ / Played at</label><input type="datetime-local" value={form.played_at} onChange={event=>setForm(current=>({...current,played_at:event.target.value}))}/></div><div className="field"><label>Best of</label><select value={form.best_of} onChange={event=>setForm(current=>({...current,best_of:Number(event.target.value) as 3|5}))}><option value={3}>Best of 3</option><option value={5}>Best of 5</option></select></div><div className="field"><label>Giải đấu / Competition</label><input value={form.competition} onChange={event=>setForm(current=>({...current,competition:event.target.value}))}/></div><div className="field"><label>Địa điểm / Venue</label><input value={form.venue} onChange={event=>setForm(current=>({...current,venue:event.target.value}))}/></div><div className="field"><label>Đội nhà / Home team</label><input value={form.home_team_name} onChange={event=>setForm(current=>({...current,home_team_name:event.target.value}))}/></div><div className="field"><label>Đội khách / Away team</label><input value={form.away_team_name} onChange={event=>setForm(current=>({...current,away_team_name:event.target.value}))}/></div><div className="field"><label>Vai trò đội / Team side</label><select value={form.is_home?"home":"away"} onChange={event=>setHomeTeam(event.target.value==="home")}><option value="home">Đội nhà / Home</option><option value="away">Đội khách / Away</option></select></div><div className="field"><label>Trạng thái / Status</label><select value={form.status} onChange={event=>setForm(current=>({...current,status:event.target.value as MatchStatus}))}>{statuses.map(status=><option value={status} key={status}>{statusLabels[status]}</option>)}</select></div><div className="field" style={{gridColumn:"1/-1"}}><label>Ghi chú / Notes</label><textarea rows={2} value={form.notes} onChange={event=>setForm(current=>({...current,notes:event.target.value}))}/></div></div>
    <h3 style={{marginTop:24}}>Tỷ số từng set / Set Scores</h3><div className="set-score-grid">{sets.slice(0,maxSets).map(set=><div className="set-score-row" key={set.set_number}><b>Set {set.set_number}</b><span>{form.home_team_name||"Home"}</span><input type="number" min="0" step="1" value={set.home_score} onChange={event=>updateSet(set.set_number,"home_score",Number(event.target.value))}/><em>–</em><input type="number" min="0" step="1" value={set.away_score} onChange={event=>updateSet(set.set_number,"away_score",Number(event.target.value))}/><span>{form.away_team_name||"Away"}</span></div>)}</div><div className="notice">Tỷ số trận tự tính: {homeSets}–{awaySets}. Set 0–0 được xem là chưa nhập và không ghi mới.</div>
    <h3 style={{marginTop:24}}>Đội hình trận đấu / Match Roster</h3><div className="roster-editor">{players.map(player=>{const item=roster[player.id],selected=Boolean(item);return <div className="roster-edit-row" key={player.id}><label><input type="checkbox" checked={selected} disabled={item?.persisted} onChange={event=>togglePlayer(player.id,event.target.checked)}/><strong>#{player.jersey_number} {player.full_name}</strong><small>{player.position}</small></label><label><input type="checkbox" checked={item?.starter??false} disabled={!selected} onChange={event=>updateRoster(player.id,"starter",event.target.checked)}/> Starter</label><div className="field"><label>Sets played</label><input type="number" min="0" max={actualSetCount||form.best_of} step="1" value={item?.sets_played??0} disabled={!selected} onChange={event=>updateRoster(player.id,"sets_played",Number(event.target.value))}/></div></div>})}</div>{mode==="edit"&&initialRoster.length>0&&<small style={{color:"var(--muted)"}}>Cầu thủ đã lưu không thể bỏ khỏi roster ở bước này; có thể chỉnh Starter và Sets played.</small>}
    {error&&<div className="login-error" role="alert" style={{marginTop:16}}>{error}</div>}<div className="form-actions"><button className="secondary-btn" type="button" disabled={saving} onClick={onClose}>Hủy / Cancel</button><button className="primary-btn" type="submit" disabled={saving}>{saving?"Đang lưu…":"Lưu / Save"}</button></div></form></section></div>;
}

export const matchToForm=(match:{played_at:string;competition:string|null;venue:string|null;home_team_name:string;away_team_name:string;is_home:boolean;best_of:number;status:string;notes:string|null}):MatchFormValue=>({played_at:toLocalDateTime(match.played_at),competition:match.competition??"",venue:match.venue??"",home_team_name:match.home_team_name,away_team_name:match.away_team_name,is_home:match.is_home,best_of:match.best_of as 3|5,status:match.status as MatchStatus,notes:match.notes??""});
