"use client";

import { useState } from "react";

export const playerPositions=["setter","outside_hitter","opposite","middle_blocker","libero","defensive_specialist"] as const;
export type PlayerPosition=typeof playerPositions[number];
export type PlayerFormValue={full_name:string;jersey_number:number;position:PlayerPosition;height_cm:number|null;is_active:boolean};

const labels:Record<PlayerPosition,string>={setter:"Chuyền 2 / Setter",outside_hitter:"Chủ công / Outside Hitter",opposite:"Đối chuyền / Opposite",middle_blocker:"Phụ công / Middle Blocker",libero:"Libero",defensive_specialist:"Chuyên gia phòng thủ / Defensive Specialist"};
const defaults:PlayerFormValue={full_name:"",jersey_number:0,position:"outside_hitter",height_cm:null,is_active:true};

export function PlayerFormModal({mode,initialValue,onClose,onSave}:{mode:"create"|"edit";initialValue?:PlayerFormValue;onClose:()=>void;onSave:(value:PlayerFormValue)=>Promise<string|null>}){
  const [form,setForm]=useState<PlayerFormValue>(initialValue??defaults);
  const [error,setError]=useState("");
  const [saving,setSaving]=useState(false);
  async function submit(event:React.FormEvent){event.preventDefault();if(saving)return;const name=form.full_name.trim();if(!name){setError("Tên cầu thủ không được để trống.");return}if(!Number.isInteger(form.jersey_number)||form.jersey_number<0||form.jersey_number>99){setError("Số áo phải là số nguyên từ 0 đến 99.");return}if(!playerPositions.includes(form.position)){setError("Vị trí cầu thủ không hợp lệ.");return}if(form.height_cm!==null&&(!Number.isInteger(form.height_cm)||form.height_cm<100||form.height_cm>250)){setError("Chiều cao phải là số nguyên từ 100 đến 250 cm.");return}setSaving(true);setError("");const saveError=await onSave({...form,full_name:name});if(saveError){setError(saveError);setSaving(false)}}
  return <div className="modal-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)onClose()}}><section className="modal-card" role="dialog" aria-modal="true" aria-labelledby="player-form-title"><div className="panel-head"><div><h2 id="player-form-title">{mode==="create"?"Thêm cầu thủ / Add Player":"Chỉnh sửa cầu thủ / Edit Player"}</h2><p>Dữ liệu được lưu trực tiếp vào Supabase.</p></div><button className="icon-btn" type="button" aria-label="Đóng" disabled={saving} onClick={onClose}>×</button></div><form onSubmit={submit} className="form-section" style={{marginTop:20}}><div className="form-grid" style={{gridTemplateColumns:"1fr 1fr"}}><div className="field" style={{gridColumn:"1 / -1"}}><label htmlFor="player-full-name">Tên cầu thủ / Full name</label><input id="player-full-name" value={form.full_name} onChange={event=>setForm(current=>({...current,full_name:event.target.value}))} required/></div><div className="field"><label htmlFor="player-number">Số áo / Jersey number</label><input id="player-number" type="number" min="0" max="99" step="1" value={form.jersey_number} onChange={event=>setForm(current=>({...current,jersey_number:Number(event.target.value)}))}/></div><div className="field"><label htmlFor="player-height">Chiều cao / Height (cm)</label><input id="player-height" type="number" min="100" max="250" step="1" value={form.height_cm??""} placeholder="Không bắt buộc" onChange={event=>setForm(current=>({...current,height_cm:event.target.value===""?null:Number(event.target.value)}))}/></div><div className="field" style={{gridColumn:"1 / -1"}}><label htmlFor="player-position">Vị trí / Position</label><select id="player-position" value={form.position} onChange={event=>setForm(current=>({...current,position:event.target.value as PlayerPosition}))}>{playerPositions.map(position=><option value={position} key={position}>{labels[position]}</option>)}</select></div><label className="player-active-field"><input type="checkbox" checked={form.is_active} onChange={event=>setForm(current=>({...current,is_active:event.target.checked}))}/><span>Đang hoạt động / Active</span></label></div>{error&&<div className="login-error" role="alert" style={{marginTop:14}}>{error}</div>}<div className="form-actions"><button className="secondary-btn" type="button" disabled={saving} onClick={onClose}>Hủy / Cancel</button><button className="primary-btn" type="submit" disabled={saving}>{saving?"Đang lưu…":mode==="create"?"Thêm cầu thủ / Add":"Lưu thay đổi / Save"}</button></div></form></section></div>;
}
